services:
  - type: web
    name: sales-management
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Sales Management System"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://sales.onrender.com"
      - key: DB_CONNECTION
        value: "sqlite"
      - key: SESSION_DRIVER
        value: "file"
      - key: CACHE_DRIVER
        value: "file"
      - key: QUEUE_CONNECTION
        value: "sync"
      - key: LOG_LEVEL
        value: "error"
    buildCommand: |
      composer install --no-interaction --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php artisan storage:link
      php-fpm 